# Google App Engine configuration for ChainWeave AI Backend
runtime: nodejs20

# Environment variables (use Cloud Console for sensitive values)
env_variables:
  NODE_ENV: production
  PORT: 8080

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Resource allocation
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Health check configuration
readiness_check:
  path: '/health'
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: '/health'
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Enable Cloud Build API
includes:
  - node_modules

# Skip files for faster deployment
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?tests?/.*$
  - ^(.*/)?test/.*$
  - ^(.*/)?.*\.md$
  - ^(.*/)?\.git/.*$
  - ^(.*/)?\.github/.*$
  - ^(.*/)?node_modules/.*/test/.*$
  - ^(.*/)?node_modules/.*/tests/.*$
