"use client"

import { motion } from "framer-motion"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

const stats = [
  {
    value: "10,000+",
    label: "NFTs Created",
    description: "Unique digital assets generated by our AI"
  },
  {
    value: "5+",
    label: "Supported Chains",
    description: "Cross-chain compatibility across major networks"
  },
  {
    value: "1,500+",
    label: "Active Creators",
    description: "Artists and developers using our platform"
  },
  {
    value: "99.9%",
    label: "Uptime",
    description: "Reliable service with minimal downtime"
  }
]

const chainSupport = [
  { name: "Ethereum", status: "Live" },
  { name: "BSC", status: "Live" },
  { name: "Polygon", status: "Live" },
  { name: "ZetaChain", status: "Native" },
  { name: "Arbitrum", status: "Coming Soon" },
  { name: "Optimism", status: "Coming Soon" }
]

export function StatsSection() {
  return (
    <section className="py-20 px-4 sm:px-6 lg:px-8 bg-muted/30">
      <div className="container mx-auto">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <Badge 
            variant="outline" 
            className="mb-4 px-4 py-2 text-sm font-medium border-primary/20 bg-primary/5 text-primary"
          >
            Platform Statistics
          </Badge>
          
          <h2 className="text-3xl sm:text-4xl font-bold mb-6">
            Trusted by creators
            <span className="text-primary block">worldwide</span>
          </h2>
          
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Join thousands of creators who have already discovered the power of 
            AI-driven cross-chain NFT creation.
          </p>
        </motion.div>

        {/* Stats Grid */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-6 mb-16">
          {stats.map((stat, index) => (
            <motion.div
              key={stat.label}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              viewport={{ once: true }}
            >
              <Card className="text-center border-0 bg-background/50 hover:bg-background/80 transition-all duration-300">
                <CardContent className="p-6">
                  <motion.div
                    initial={{ scale: 0.5 }}
                    whileInView={{ scale: 1 }}
                    transition={{ duration: 0.5, delay: index * 0.1 + 0.2 }}
                    viewport={{ once: true }}
                    className="text-3xl sm:text-4xl font-bold text-primary mb-2"
                  >
                    {stat.value}
                  </motion.div>
                  <h3 className="text-lg font-semibold mb-2">{stat.label}</h3>
                  <p className="text-sm text-muted-foreground">{stat.description}</p>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>

        {/* Chain Support */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
          className="text-center"
        >
          <h3 className="text-xl font-semibold mb-8">Supported Blockchain Networks</h3>
          
          <div className="flex flex-wrap justify-center gap-4 max-w-4xl mx-auto">
            {chainSupport.map((chain, index) => (
              <motion.div
                key={chain.name}
                initial={{ opacity: 0, scale: 0.8 }}
                whileInView={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                viewport={{ once: true }}
                className="flex items-center space-x-3 bg-background/50 rounded-full px-6 py-3 border"
              >
                <span className="font-medium">{chain.name}</span>
                <Badge 
                  variant={chain.status === "Native" ? "default" : chain.status === "Live" ? "secondary" : "outline"}
                  className={`text-xs ${
                    chain.status === "Native" 
                      ? "bg-primary text-primary-foreground" 
                      : chain.status === "Live" 
                        ? "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/20 dark:text-emerald-400" 
                        : ""
                  }`}
                >
                  {chain.status}
                </Badge>
              </motion.div>
            ))}
          </div>
        </motion.div>
      </div>
    </section>
  )
}
